from rest_framework.decorators import api_view, permission_classes
import openai
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from inventory.models import InventoryItem
from .utils import gpt_utils


@api_view(['POST'])
@permission_classes([IsAuthenticated])
def suggest_recipe(request):
    """
    API endpoint for generating recipe suggestions based on user input.
    Requires user authentication.
    """
    # # Validate API Key
    if not gpt_utils.OPENAI_API_KEY:
        return Response({"error": "API key not configured"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    # Extract user details
    user = request.user
    gpt_utils.logger.info(f"Recipe request by user: {user.username}")

    # Extract and validate input data
    ingredients = request.data.get(
        'ingredients',
        list(InventoryItem.objects.filter(added_by=user.id).values('name', 'unit', 'quantity', 'expiration_date'))
    )
    cuisine = request.data.get('cuisine', 'any')
    spicy_level = request.data.get('spicy_level', 'medium')
    cooking_time = request.data.get('cooking_time', 'any')

    if not ingredients:
        return Response({"error": "'ingredients' field is required"}, status=status.HTTP_400_BAD_REQUEST)

    try:
        # Generate recipe synchronously
        recipe = gpt_utils.generate_recipe(ingredients, cuisine, spicy_level, cooking_time)
        return Response({
            "user": {
                "username": user.username,
                "email": user.email,
            },
            "recipe": recipe
        }, status=status.HTTP_200_OK)
    except openai.OpenAIError as e:
        return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

@api_view(['POST'])
@permission_classes([IsAuthenticated])
def save_recipe(request):
    """
    API endpoint for saving a recipe generated by the user.
    Requires user authentication.
    """
    # Extract and validate recipe data from the request
    recipe_data = request.data
    if not recipe_data or not all(field in recipe_data for field in ['name', 'ingredients', 'instructions']):
        return Response({"error": "'recipe' field with 'name', 'ingredients', and 'instructions' is required"}, 
                        status=status.HTTP_400_BAD_REQUEST)

    try:
        # Save the recipe to the database (implemented directly here)
        from recipes.models import Recipe
        saved_recipe = Recipe.objects.create(
            name=recipe_data['name'],
            ingredients=recipe_data['ingredients'],
            instructions=recipe_data['instructions'],
            created_by=request.user
        )
        return Response({
            "message": "Recipe saved successfully",
            "recipe": saved_recipe
        }, status=status.HTTP_201_CREATED)
    except Exception as e:
        gpt_utils.logger.error(f"Error saving recipe: {str(e)}")
        return Response({"error": "Failed to save the recipe"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    
from recipes.models import Recipe

@api_view(['GET'])
@permission_classes([IsAuthenticated])
def get_list_recipes(request):
    """
    API endpoint to get a list of all saved recipes created by the authenticated user.
    Requires user authentication.
    """
    try:
        user = request.user
        recipes = Recipe.objects.filter(created_by=user).values('id', 'name', 'ingredients', 'instructions')
        return Response({
            "user": {
                "username": user.username,
                "email": user.email,
            },
            "recipes": list(recipes)
        }, status=status.HTTP_200_OK)
    except Exception as e:
        gpt_utils.logger.error(f"Error retrieving recipes: {str(e)}")
        return Response({"error": "Failed to retrieve recipes"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    